# These are supported funding model platforms

github: EDGECASE-1
patreon: # Replace with actual Patreon
open_collective: # Replace with actual Open Collective
ko_fi: # Replace with actual Ko-fi
tidelift: # Replace with actual Tidelift
community_bridge: # Replace with actual Community Bridge
liberapay: # Replace with actual Liberapay
issuehunt: # Replace with actual IssueHunt
lfx_crowdfunding: # Replace with actual LFX Crowdfunding
polar: # Replace with actual Polar
custom: ['https://edgecase-1.github.io/NeuralCline/#pricing']